name: CI/CD for Flask Ajher Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/ajher-409804/ajher_model:${{ github.sha }} .
          docker tag gcr.io/ajher-409804/ajher_model:${{ github.sha }} gcr.io/ajher-409804/ajher_model:latest
          docker push gcr.io/ajher-409804/ajher_model:${{ github.sha }}
          docker push gcr.io/ajher-409804/ajher_model:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ajher_model
          image: gcr.io/ajher-409804/ajher_model:${{ github.sha }}
          project: ajher-409804
          region: asia-southeast2
          platform: managed
          allow-unauthenticated: true
          env-vars: |
            model=indobenchmark/indobert-base-p2
            PORT=5000
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY_FILE }}
