name: CI/CD for Flask Ajher Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/ajher-409804/ajher_model:${{ github.sha }} .
          docker tag gcr.io/ajher-409804/ajher_model:${{ github.sha }} gcr.io/ajher-409804/ajher_model:latest
          docker push gcr.io/ajher-409804/ajher_model:${{ github.sha }}
          docker push gcr.io/ajher-409804/ajher_model:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY_FILE }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ajher_model \
            --image=gcr.io/ajher-409804/ajher_model:${{ github.sha }} \
            --platform=managed \
            --region=asia-southeast2 \
            --allow-unauthenticated \
            --set-env-vars=model=indobenchmark/indobert-base-p2,PORT=5000
